### ISSUE TITLE
Review background network activity

### ISSUE THREAD

**Issue by bplimley** [bearing/dosenet-raspberrypi#12]
The system log of the Etcheverry test device shows a lot of network activity repeating every minute. Some of it may be related to the ad hoc setup, and some of it may be from other stuff going on, but it would be nice to clean up the constant background logging... save network activity and save disk space (from the log).

**Comment by alihanks** [comment]
Do you have any more thoughts on this, do you still consider it something we should try and resolve?

**Comment by bplimley** [comment]
No, at this point it doesn't really matter. If you wanted to use `/var/log/messages` more or put `/var/log` on the actual disk instead of RAM, then it could matter.
