### ISSUE TITLE
"dosenet.sh stop" should turn off LEDs

### ISSUE THREAD

**Issue by bplimley** [bearing/dosenet-raspberrypi#14]
Currently, stopping the dosenet service runs "killall python", and does stop udp_sender and dosimeter.py, but the LEDs are left on.

**Comment by jccurtis** [comment]
See https://nattster.wordpress.com/2013/06/05/catch-kill-signal-in-python/

import signal
import sys

def signal_term_handler(signal, frame):
    print 'got SIGTERM'
    sys.exit(0)

signal.signal(signal.SIGTERM, signal_term_handler)
