### ISSUE TITLE
Graph all location together

### ISSUE THREAD

**Issue by alihanks** [bearing/dosenet-raspberrypi#17]
Add graph that shows all locations, with option to select which locations to show, averaged over different time windows, etc.

**Comment by jccurtis** [comment]
Where is this plot found?

**Comment by alihanks** [comment]
Right now it's here: https://radwatch.berkeley.edu/dosenet/data
I haven't decided where we should put it more permanently.... and it could use a little work.

**Comment by jccurtis** [comment]
Nice one, are you plotting all of the data? Have you found a limit to dygraphs max plottable points?

**Comment by alihanks** [comment]
Well, this example is only plotting the last month. The downloads page plots all the data for each location separately and is fine so far. I think the limiting factor is simply the more data the longer it takes to load.

I have noticed that some of the interactive features don't work as smoothly when there are a  lot of points, but they do still work.
