### ISSUE TITLE
use time.time() instead of datetime's

### ISSUE THREAD

**Issue by bplimley** [bearing/dosenet-raspberrypi#28]
For the event timestamps to be unambiguous regardless of timezone settings in the Pi system.

**Comment by jccurtis** [comment]
I think we should create the time on the pi in UNIX time but then store a
date time (made from this UNIX time) in the local sql database. This way
loading and querying locally is easy and the transmitted data contains the
UNIX time. We should integrate some of the tools I sent on slack (probably
clean them up) to transparently translate timestamps.

On Monday, April 11, 2016, Brian Plimley notifications@github.com wrote:

> For the event timestamps to be unambiguous regardless of timezone settings
> in the Pi system.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/bearing/dosenet-raspberrypi/issues/28

## 

Joey http://jccurtis.github.io/

**Comment by bplimley** [comment]
Sure. Right now everything is just a float from time.time(). I'm going to finish the basic code before adding buffering and timestamps to server, so I'll integrate your tools at that point. Thanks for the input!
