### ISSUE TITLE
Handout for Nuclear Science Day

### ISSUE THREAD

**Issue by alihanks** [bearing/dosenet-raspberrypi#29]

**Comment by jccurtis** [comment]
@alihanks Do you want to template something out?

**Comment by alihanks** [comment]
Yeah, I'll put something together today.

**Comment by jccurtis** [comment]
Did you get feedback from Erika?

On Fri, Apr 22, 2016 at 10:58 AM, Ali Hanks notifications@github.com
wrote:

> Closed #29 https://github.com/bearing/dosenet-raspberrypi/issues/29.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/bearing/dosenet-raspberrypi/issues/29#event-638041917

## 

Joey http://jccurtis.github.io/

**Comment by alihanks** [comment]
Yep.
