### ISSUE TITLE
Move stationID configuration to a Google doc

### ISSUE THREAD

**Issue by bplimley** [bearing/dosenet-raspberrypi#37]
Right now, `git-pull-reboot.sh` contains the configuration of which station ID should be on which branch. However, this is messy because `git-pull-reboot.sh` is itself in the git repo. So there is potential for weird things to happen, like checkout master, then master says checkout dev, then dev says checkout master... Joey and Brian talked about this.

**Comment by bplimley** [comment]
Actually, it is probably better to do this in the MySQL `stations` table, and have a TCP request from the device in `git-pull-reboot.sh` via python somehow.

**Comment by alihanks** [comment]
Since this is now in the DB do we want to close/change this issue to be using the DB flags?

**Comment by bplimley** [comment]
Sure.
