### ISSUE TITLE
New dosenet.sh option: Record counts to a local file instead of sending packets

### ISSUE THREAD

**Issue by bplimley** [bearing/dosenet-raspberrypi#6]
This would be useful for certain calibration or testing situations.

**Comment by jccurtis** [comment]
I agree, we could also use similar infrastructure for sending groups of CPM instead of only the current CPM

**Comment by bplimley** [comment]
Tyler is working on this now. 
Notes and requirements:
- argparse option to enable local data logging
- argparse option to specify file
- default data log file in `/home/pi/` (defined in `globalvalues.py`)
- writing CPM to file should be performed in a method of `manager.py` and called from handle_cpm()
- function to read the data log file from disk (put this in `auxiliaries.py`)
- test writing function and reading function in `tests.py`
