### ISSUE TITLE
Add timeout on NTP wait on boot

### ISSUE THREAD

**Issue by bplimley** [bearing/dosenet-raspberrypi#68]
`dosenet.sh` waits for NTP to sync before starting `manager.py`, which is the intended behavior (see issue #42). However, we also need a timeout on this wait, in case the network is actually down, so that `manager.py` will still run and log data to disk.

**Comment by bplimley** [comment]
I don't know how to do this in bash. If we handle this in python (as part of `manager.py`'s `__main__` script), we would probably have to run the shell commands in a subprocess and run a timer in the main process.

**Comment by tybtab** [comment]
I got this working. 
sudo service ntp stop
sudo timeout 60s ntpd -gq
sudo service ntp start

If internet is down, the second command will timeout after 60 seconds. Then manager will start up like normal without ntp update.

**Comment by tybtab** [comment]
If internet is up, it will complete those commands within 60 seconds.
