### ISSUE TITLE
device reboot at end of counting period

### ISSUE THREAD

**Issue by alihanks** [bearing/dosenet-raspberrypi#69]
See issue dosenet #107
Want the device to wait for current counting period to end before rebooting based on returned status from the server
Should do this all in python

**Comment by tybtab** [comment]
Currently, if manager catches a sigquit signal, it will wait for the counting period to end before manager safely takes it self down for reboot (this was implemented over the summer). How should I replicate this process using python since sending a sigquit signal is not in python.

**Comment by tybtab** [comment]
I found a way. When does the device reboot 12:00 AM pacific time?

**Comment by bplimley** [comment]
Yes, all devices reboot at 0800 UTC which is 12am PST and 1am PDT (which is right now).

If the rebooting is handled in python, you don't need a sigquit signal. The signal was to make a way to communicate from bash to python.

**Comment by bplimley** [comment]
So Ali and I were discussing and clarified a few things about how the various reboot things should work.

Rather than calling `os.system('sudo shutdown now -r')`, you should run `git-pull-reboot.sh` when you are ready to shutdown. This will handle the git updating and then do the reboot.

**Comment by tybtab** [comment]
Ok I changed it to run git-pull-reboot.sh and it runs fine.
