### ISSUE TITLE
Fix bug with timestamps sent to memory

### ISSUE THREAD

**Issue by bplimley** [bearing/dosenet-raspberrypi#72]
`DataHandler.send_to_queue()` takes `cpm` and `cpm_err` as inputs, and assigns a timestamp using `time.time()`.

The problem is, if the data is loaded from the queue and then fails to send, it goes back into the queue with the wrong timestamp. Instead, the timestamp should be an input argument to `send_to_queue()` and `send_to_memory()`.

**Comment by tybtab** [comment]
I think I solved this with the 'new' protocol issue.

**Comment by tybtab** [comment]
Also 'new' protocol is still not default. Should I make it 'default'?

**Comment by bplimley** [comment]
It looks like this is fixed in your pull request, Thanks.
I'm still holding off on making `new` default until a couple more issues are resolved, such as #68. Sorry I forgot to assign you earlier.
