### ISSUE TITLE
Getting the RPi IP address via Email

### ISSUE THREAD

**Issue by jccurtis** [bearing/dosenet-raspberrypi#8]
Add feature so that whenever the pi starts it sends an email to dosenet that says hi and gives its IP address.

Check out: http://elinux.org/RPi_Email_IP_On_Boot_Debian

**Comment by bplimley** [comment]
We decided not to do this, because it would require putting Gmail login credentials in the public repo, or else trying to run an email server on the pi which will probably be blocked as spam by everything.
