### ISSUE TITLE
git-pull-reboot root ownership workaround

### ISSUE THREAD

**Issue by bplimley** [bearing/dosenet-raspberrypi#97]
If a `git pull` is performed as root, for example within the `sudo screen` that the regular `manager.py` runs in, then certain files in `.git/objects/` will be owned by root and have read-only access to the default user. Then `git pull` under the default user within `git-pull-reboot.sh` will fail due to insufficient permissions, and the device will not update.

However, since `git-pull-reboot.sh` runs under `sudo` anyway, the script should check for a failed pull and then do a `chown` to fix it.

**Comment by alihanks** [comment]
Do you know if this has been resolved?

**Comment by bplimley** [comment]
I don't think it has. Up to you whether it's worth resolving or not, as an edge case for usage.
